### PR TITLE
8.2 xcpng build

### PR DESCRIPTION
**Pull request by tescande**

### CODE REVIEW

**Review by stormi — APPROVED** [review]

**Comment by tescande** [comment]
> Since the end result is strictly the same, wouldn't it make sense to just fork `XS-8.2` off current master?

This is what I proposed to Sam but he preferred 2 separated branches :)

**Comment by stormi** [comment]
Fork XS-8.2 off master? But master has diverged from XS-8.3 already. I don't follow.

**Comment by tescande** [comment]
> Fork XS-8.2 off master? But master has diverged from XS-8.3 already. I don't follow.

Both master and (future) 8.2 branches are almost the same. So to not duplicate the tarball and patches, we could have XS-8.2 and XS-8.3 to be the same.

And this is the only difference between master and 8.2:
```
$ git diff master..8.2-xcpng-build
diff --git a/SPECS/openssh.spec b/SPECS/openssh.spec
index 997a64d..66591d9 100644
--- a/SPECS/openssh.spec
+++ b/SPECS/openssh.spec
@@ -655,7 +655,7 @@ getent passwd sshd >/dev/null || \
 %endif
 
 %changelog
-* Tue Apr 30 2024 Thierry Escande <thierry.escande@vates.tech> - 7.4p1-23.2.1 + 0.10.3-2.23.2.1
+* Tue May 13 2024 Thierry Escande <thierry.escande@vates.tech> - 7.4p1-23.2.1 + 0.10.3-2.23.2.1
 - Harden default ciphers and algorithms
 - Disable GSSAPIAuthentication in sshd_config
 - Remove build dependency on xauth (used for X11 forwarding not supported on XCP-ng hosts)
```

**Comment by stormi** [comment]
So you were talking about 8.2, not XS-8.2. I don't see what this brings us (except having to pay attention, each time we'll merge a PR towards either master or 8.2, not to create a merge commit, until they do start diverging), but as long as the 8.2 has an history that goes back to XS-8.2 and master an history that goes back to XS-8.3 (which will be the case if both XS- branches are identical), this can be done.

But you'd have to lie on the date for 8.2, which would increase the gap between the changelog date and the RPM build date.

**Review by benjamreis — APPROVED** [review]

**Comment by tescande** [comment]
Ok, so let it as it is now to keep the 8.2 changelog date close to its build.

**Comment by tescande** [comment]
Koji build: [openssh-7.4p1-23.2.1.xcpng8.2](https://koji.xcp-ng.org/buildinfo?buildID=3242)

**Pull request merged**
